pull_request_rules:
  - name: automatic merge dependabot on Vercel build pass
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Vercel
    actions:
      merge:
        method: rebase

  - name: automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase