name: アイドルマスター シンデレラガールズ スターライトステージ
developer: BANDAI NAMCO
platform:
  android: jp.co.bandainamcoent.BNEI0242
  ios: https://itunes.apple.com/jp/app/aidorumasuta-shindereragaruzu/id1016318735
website: https://cinderella.idolmaster.jp/sl-stage/
