name: アイドルマスター シンデレラガールズ スターライトステージ
aka:
  - CGSS
  - デレステ
developer: BANDAI NAMCO
platform:
  android: jp.co.bandainamcoent.BNEI0242
  ios: https://itunes.apple.com/jp/app/aidorumasuta-shindereragaruzu/id1016318735
website: https://cinderella.idolmaster.jp/sl-stage/
mapPolicy:
  hasGivenMap: true
  hasPaidMap: unknown
  hasFreeWorkMap: true
  hasLimitedPurchaseMap: unknown
  hasLimitedExpiringMap: unknown
  hasLimitedFreeMap: unknown
  difficultiesRequireSeperateUnlock: true
scorePolicy:
  comboDependent: unknown
  nonPlayerDependent: true
socialPolicy:
  hasSocial: true
  hasMultiPlay: true
  hasFriendRanking: unknown
  hasGlobalRanking: unknown
  hasEventRanking: unknown
