name: D4DJ Groovy Mix
aka:
  - グルミク
developer: Bushimo
platform:
  android: com.bushiroad.d4dj
  ios: https://apps.apple.com/jp/app/id1490381755
website: https://d4dj.bushimo.jp/
gameplayPolicy:
  hasFail: true
  gameDimension: 1
  trackCount:
    - 6
    - 这里包含了两侧的音轨。
  linearTrack: true
  hasFlip: true
mapPolicy:
  hasPaidMap: false
  hasFreeWorkMap: true
  hasLimitedPurchaseMap: false
  hasLimitedExpiringMap: false
  hasLimitedFreeMap: false
  difficultiesRequireSeperateUnlock: false
scorePolicy:
  comboDependent: unknown
  nonPlayerDependent: true
  flatMaxScore: false
socialPolicy:
  hasSocial: true
  hasMultiPlay: true
  hasFriendRanking: false
  hasGlobalRanking: false
  hasEventRanking: true
