name: Arcaea
developer: Lowiro
tagline: 创新立体节奏游戏
platform:
  android: moe.low.arc
  ios: https://apps.apple.com/us/app/arcaea/id1205999125
website: https://arcaea.lowiro.com
gameplayPolicy:
  hasFail:
    - true
    - 使用 Hard 模式的角色，在回亿率为 0 时将被直接判定为失败。
  gameDimension: 1
  trackCount: 4
  linearTrack: true
  hasFlip: false
mapPolicy:
  hasPaidMap: true
  hasFreeWorkMap: true
  hasLimitedPurchaseMap: false
  hasLimitedExpiringMap: false
  hasLimitedFreeMap:
    - true
    - 指 World Extend 曲包。
  difficultiesRequireSeperateUnlock: true
scorePolicy:
  comboDependent: false
  nonPlayerDependent: false
socialPolicy:
  hasSocial: true
  hasMultiPlay: false
  hasFriendRanking: true
  hasGlobalRanking: true
  hasEventRanking: false
