name: Arcaea
developer: Lowiro
tagline: 创新立体节奏游戏
platform:
  android: moe.low.arc
  ios: https://apps.apple.com/us/app/arcaea/id1205999125
website: https://arcaea.lowiro.com
mapPolicy:
  hasGivenMap: true
  hasPaidMap: true
  hasFreeWorkMap: true
  hasLimitedPurchaseMap: "partial"
  hasLimitedExpiringMap: "unknown"
  hasLimitedFreeMap: true
  difficultiesRequireSeperateUnlock: true
scorePolicy:
  comboDependent: false
  nonPlayerDependent: false
socialPolicy:
  hasSocial: true
  hasMultiPlay: false
  hasFriendRanking: true
  hasGlobalRanking: true
  hasEventRanking: false
